// Generated by `pnpm sign-screenshots` (scripts/sign-link-screenshots.ts). Do not edit by hand.
// Maps normalized ScreenshotLink target URLs (from src/lib/projects.tsx) to their
// build-time signed /api/link-screenshot URLs. Committed so the build/typecheck
// resolve the import; empty when LINK_SCREENSHOT_SIGNING_KEY is unset.
export const linkScreenshotUrls: Record<string, string> = {}
