// Generated by `pnpm stars` (scripts/fetch-stars.ts). Do not edit by hand.
// Keyed by lowercase `owner/repo`. Committed so the build never calls the
// GitHub API — refresh with `pnpm stars` and commit the result.
export const stars: Record<string, number> = {
  'ndom91/home26': 0,
  'ndom91/llama-dash': 7,
  'ndom91/open-plan-annotator': 68,
  'nextauthjs/next-auth': 28270,
}
