/**
 * Fetch GitHub star counts for every project repo and write them to
 * `src/lib/stars.generated.ts`, committed to the repo so the Cloudflare build
 * never calls the GitHub API (same pattern as the pre-rendered mermaid SVGs).
 *
 * Run with: `pnpm stars`
 * Optional: set `GITHUB_TOKEN` to raise the unauthenticated rate limit.
 *
 * On a fetch failure the previous committed value is kept, so a flaky network
 * or rate limit never clobbers good data with zeros.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { repoSlug } from '../src/lib/repo-slug.ts'
import { stars as existingStars } from '../src/lib/stars.generated.ts'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = join(scriptDir, '../src/lib/stars.generated.ts')
// Scan project source for `repo:` URLs instead of importing projects.tsx, which
// node cannot load (JSX).
const PROJECTS_SOURCE_PATH = join(scriptDir, '../src/lib/projects.tsx')

function writeFileIfChanged(path: string, content: string) {
  if (readFileSync(path, 'utf8') === content) {
    return false
  }

  writeFileSync(path, content)
  return true
}

function repoUrlsFromSource(): string[] {
  const source = readFileSync(PROJECTS_SOURCE_PATH, 'utf8')
  return [...source.matchAll(/\brepo:\s*['"]([^'"]+)['"]/g)].map((match) => match[1])
}

async function fetchStarCount(slug: string): Promise<number | null> {
  const token = process.env.GITHUB_TOKEN
  const response = await fetch(`https://api.github.com/repos/${slug}`, {
    headers: {
      'User-Agent': 'ndo.dev-build',
      Accept: 'application/vnd.github+json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
  })

  if (!response.ok) {
    console.warn(`  ! ${slug}: ${response.status} ${response.statusText}`)
    return null
  }

  const data = (await response.json()) as { stargazers_count?: number }
  return typeof data.stargazers_count === 'number' ? data.stargazers_count : null
}

async function main() {
  const slugs = [
    ...new Set(
      repoUrlsFromSource()
        .map((repoUrl) => repoSlug(repoUrl))
        .filter((slug): slug is string => slug !== null)
    ),
  ]

  const stars: Record<string, number> = {}

  for (const slug of slugs) {
    const count = await fetchStarCount(slug)
    if (count === null) {
      const previous = existingStars[slug]
      if (previous !== undefined) {
        stars[slug] = previous
        console.log(`  · ${slug}: kept ${previous} (fetch failed)`)
      }
      continue
    }
    stars[slug] = count
    console.log(`  ✓ ${slug}: ${count}`)
  }

  const sorted = Object.keys(stars)
    .sort()
    .map((slug) => `  '${slug}': ${stars[slug]},`)
    .join('\n')

  const body = `// Generated by \`pnpm stars\` (scripts/fetch-stars.ts). Do not edit by hand.
// Keyed by lowercase \`owner/repo\`. Committed so the build never calls the
// GitHub API — refresh with \`pnpm stars\` and commit the result.
export const stars: Record<string, number> = {${sorted ? `\n${sorted}\n` : ''}}
`

  const changed = writeFileIfChanged(OUTPUT_PATH, body)
  const verb = changed ? 'wrote' : 'unchanged'
  console.log(`Stars: ${verb} ${Object.keys(stars).length} repo(s) in src/lib/stars.generated.ts`)
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
