/**
 * Scan `src/lib/projects.tsx` for `<ScreenshotLink url="...">` targets, sign
 * each one at build time, and write the signed `/api/link-screenshot` URLs to
 * `src/lib/link-screenshots.generated.ts` (committed, same pattern as
 * `scripts/fetch-stars.ts` / `src/lib/stars.generated.ts`).
 *
 * Run with: `pnpm sign-screenshots`
 *
 * Project links live inside JSX blurbs, so they are not part of any content
 * stream the blog pipeline scans. The site is prerendered, so previews must be
 * signed here at build time rather than per-request. When
 * `LINK_SCREENSHOT_SIGNING_KEY` is unset, an empty map is emitted and
 * `ScreenshotLink` degrades to a plain link.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { collectProjectLinkTargets } from '../src/lib/link-screenshot-targets.ts'
import { signLinkScreenshotUrls } from '../src/lib/sign-link-screenshot.ts'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const SOURCE_PATH = join(scriptDir, '../src/lib/projects.tsx')
const OUTPUT_PATH = join(scriptDir, '../src/lib/link-screenshots.generated.ts')

function generatedBody(entries: Record<string, string>) {
  const sorted = Object.keys(entries)
    .sort()
    .map((url) => `  ${JSON.stringify(url)}: ${JSON.stringify(entries[url])},`)
    .join('\n')

  return `// Generated by \`pnpm sign-screenshots\` (scripts/sign-link-screenshots.ts). Do not edit by hand.
// Maps normalized ScreenshotLink target URLs (from src/lib/projects.tsx) to their
// build-time signed /api/link-screenshot URLs. Committed so the build/typecheck
// resolve the import; unchanged when LINK_SCREENSHOT_SIGNING_KEY is unset.
export const linkScreenshotUrls: Record<string, string> = {${sorted ? `\n${sorted}\n` : ''}}
`
}

function writeFileIfChanged(path: string, content: string) {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) {
    return false
  }

  writeFileSync(path, content)
  return true
}

async function main() {
  if (!process.env.LINK_SCREENSHOT_SIGNING_KEY) {
    if (!existsSync(OUTPUT_PATH)) {
      writeFileSync(OUTPUT_PATH, generatedBody({}))
      console.warn('Link screenshots: LINK_SCREENSHOT_SIGNING_KEY unset — wrote empty map.')
    } else {
      console.warn('Link screenshots: LINK_SCREENSHOT_SIGNING_KEY unset — kept existing map.')
    }
    return
  }

  const source = readFileSync(SOURCE_PATH, 'utf8')
  const urls = collectProjectLinkTargets(source)

  const entries = await signLinkScreenshotUrls(urls)
  const changed = writeFileIfChanged(OUTPUT_PATH, generatedBody(entries))
  const verb = changed ? 'wrote' : 'unchanged'
  console.log(
    `Link screenshots: ${verb} ${Object.keys(entries).length} signed URL(s) in src/lib/link-screenshots.generated.ts`
  )
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
