/**
 * Scan `src/lib/projects.tsx` for `<ScreenshotLink url="...">` targets, sign
 * each one at build time, and write the signed `/api/link-screenshot` URLs to
 * `src/lib/link-screenshots.generated.ts` (committed, same pattern as
 * `scripts/fetch-stars.ts` / `src/lib/stars.generated.ts`).
 *
 * Run with: `pnpm sign-screenshots`
 *
 * Project links live inside JSX blurbs, so they are not part of any content
 * stream the blog pipeline scans. The site is prerendered, so previews must be
 * signed here at build time rather than per-request. When
 * `LINK_SCREENSHOT_SIGNING_KEY` is unset, an empty map is emitted and
 * `ScreenshotLink` degrades to a plain link.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildLinkScreenshotUrl, normalizeLinkScreenshotTarget } from '../src/lib/link-screenshot.ts'
import { signLinkScreenshotUrl } from '../src/lib/sign-link-screenshot.ts'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const SOURCE_PATH = join(scriptDir, '../src/lib/projects.tsx')
const OUTPUT_PATH = join(scriptDir, '../src/lib/link-screenshots.generated.ts')

// Matches `url="..."` or `url={'...'}` / `url={"..."}` on a ScreenshotLink tag.
const SCREENSHOT_LINK_URL = /<ScreenshotLink[^>]*?\burl=\{?["']([^"']+)["']\}?/g

function collectUrls(source: string): string[] {
  const urls = new Set<string>()

  for (const match of source.matchAll(SCREENSHOT_LINK_URL)) {
    const normalized = normalizeLinkScreenshotTarget(match[1])
    if (normalized) {
      urls.add(normalized)
    }
  }

  return [...urls]
}

function main() {
  const source = readFileSync(SOURCE_PATH, 'utf8')
  const urls = collectUrls(source)

  const entries: Record<string, string> = {}

  for (const normalizedUrl of urls) {
    const signature = signLinkScreenshotUrl(normalizedUrl)
    if (signature) {
      entries[normalizedUrl] = buildLinkScreenshotUrl(normalizedUrl, signature)
    }
  }

  const sorted = Object.keys(entries)
    .sort()
    .map((url) => `  ${JSON.stringify(url)}: ${JSON.stringify(entries[url])},`)
    .join('\n')

  const body = `// Generated by \`pnpm sign-screenshots\` (scripts/sign-link-screenshots.ts). Do not edit by hand.
// Maps normalized ScreenshotLink target URLs (from src/lib/projects.tsx) to their
// build-time signed /api/link-screenshot URLs. Committed so the build/typecheck
// resolve the import; empty when LINK_SCREENSHOT_SIGNING_KEY is unset.
export const linkScreenshotUrls: Record<string, string> = {${sorted ? `\n${sorted}\n` : ''}}
`

  writeFileSync(OUTPUT_PATH, body)

  if (!process.env.LINK_SCREENSHOT_SIGNING_KEY) {
    console.warn('Link screenshots: LINK_SCREENSHOT_SIGNING_KEY unset — wrote empty map.')
  } else {
    console.log(
      `Link screenshots: wrote ${Object.keys(entries).length} signed URL(s) to src/lib/link-screenshots.generated.ts`
    )
  }
}

main()
